backend:
  name: github
  repo: markisrt4/serious_photos
  branch: main
  base_url: https://photos.mrtechforge.com
  auth_endpoint: /auth

media_folder: "photos"
public_folder: "/photos"

publish_mode: simple
editorial_workflow: false

site_url: https://photos.mrtechforge.com
display_url: https://photos.mrtechforge.com

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "gallery"
    label: "Gallery"
    files:
      - name: "gallery_json"
        label: "Gallery Items"
        file: "gallery.json"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
              - label: "Caption"
                name: "caption"
                widget: "string"
